<a href="https://colab.research.google.com/github/ashirmuhd/DSA/blob/main/Nympy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy


1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np

a = np.arange(10,50).reshape(4,10)
a.shape
a[:,1]

array([11, 21, 31, 41])

2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [ ]:
a1 = np.full((3,3),5)
a2 = np.arange(1,10).reshape(3,3)
add = (a1+a2)
mul = (a1*a2)
trs = np.transpose(mul)
print("ADD :",add )
print("MUL :",mul )
print("TRS :",trs )



ADD : [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
MUL : [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
TRS : [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


 Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.


In [ ]:
a = np.random.randint(10,100,size=15)
c = 0
for i in range(len(a)):
  if a[i] > 50:
    a[i] = -1
    c +=1

print(c)


9


4. Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:X = x-min /max-min

In [ ]:
a = np.random.rand(5,4)
max_sum = np.argmax(np.sum(a,axis=1))
min = np.min(a)
max = np.max(a)
norm = a - min / max -min
print("Array :",a)
print("max row:",max_sum)
print("Norm",norm)


Array : [[0.44565477 0.0763855  0.20426779 0.55086545]
 [0.58430482 0.67265616 0.94869653 0.14513041]
 [0.32183833 0.18480034 0.17250436 0.72193715]
 [0.55899839 0.42963644 0.65687836 0.23331727]
 [0.04255276 0.49275887 0.25760984 0.24632478]]
max row: 1
Norm [[ 0.35824809 -0.01102117  0.11686112  0.46345877]
 [ 0.49689815  0.58524949  0.86128985  0.05772373]
 [ 0.23443165  0.09739366  0.08509768  0.63453047]
 [ 0.47159172  0.34222977  0.56947169  0.14591059]
 [-0.04485392  0.4053522   0.17020317  0.15891811]]


5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [ ]:

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]
print("Unique Elements:",unique)
print("Duplicate elements:", duplicates)



Unique Elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

In [ ]:
a = np.arange(1,37).reshape(6,6)
m = a[1:5,1:5]
e = m[m%2 ==0]
print("ARRAY:",a)
print("SUB_MATRIX:",m)
print("EVEN_NO_FROM_SUB_MATRIX:",e)

ARRAY: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
SUB_MATRIX: [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
EVEN_NO_FROM_SUB_MATRIX: [ 8 10 14 16 20 22 26 28]


7.Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [ ]:
a = np.arange(0,12).reshape(2,6)
b = a.flatten()
c = b.reshape(4,3)
print("ARRAY:",a)
print("FLATTEN_ARRAY",b)
print("CONVERTED ARRAY:",c)


ARRAY: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
FLATTEN_ARRAY [ 0  1  2  3  4  5  6  7  8  9 10 11]
CONVERTED ARRAY: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8. Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5,6])
c = np.array([ [7] , [8] , [9]])
d = np.vstack((a,b))
e = np.hstack((d,c))
print("ARRAY",a)
print("NEW ROW:",d)
print("NEW COL:",e)

ARRAY [[1 2]
 [3 4]]
NEW ROW: [[1 2]
 [3 4]
 [5 6]]
NEW COL: [[1 2 7]
 [3 4 8]
 [5 6 9]]


9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.concatenate((a,b,c))
e = d.reshape(3,3)
f = np.diag(e)
print("JOINED ARRAY :",d)
print("RESHAPED :",e)
print("DIAGONAL_ELEMENTS",f)

JOINED ARRAY : [1 2 3 4 5 6 7 8 9]
RESHAPED : [[1 2 3]
 [4 5 6]
 [7 8 9]]
DIAGONAL_ELEMENTS [1 5 9]


10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [ ]:
a = np.arange(1,21)
b = a[(a %3 == 0) |(a % 5 ==0)]
c = b.size
print("ARRAY :",a)
print("DIV:",b)
print("COUNT_DIV:",c)

ARRAY : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
DIV: [ 3  5  6  9 10 12 15 18 20]
COUNT_DIV: 9


Pandas

1. Load the Titanic dataset and display the first 10 rows.

In [3]:
import seaborn as sns
data = sns.load_dataset("titanic")
row = data.head(10)
row

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

2. Find the number of missing values in each column.

In [6]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

3.Find the percentage of passengers who survived, grouped by gender.

In [7]:
data.groupby('sex')['survived'].mean() * 100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

4 Find the average, median, and standard deviation of passenger ages.

In [13]:
a = data['age'].mean()
b = data['age'].median()
c = data['age'].std()
print("AVG:",a)
print("MEDIAN:",b)
print("SD",c)

AVG: 29.69911764705882
MEDIAN: 28.0
SD 14.526497332334044


5.Count how many passengers were in each class (pclass).

In [14]:
data['pclass'].value_counts()


pclass
3    491
1    216
2    184
Name: count, dtype: int64

6.Show all passengers who were female, under age 18, and survived.

In [16]:
data[(data['sex'] == 'female') & (data['age'] < 18) & (data['survived'] == 1)]

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

7. Replace missing age values with the median age.

In [25]:
import pandas as pd
median_age = data['age'].median()
data['age'].fillna(median_age, inplace=True)
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

8.Create a column age_group with values:
a. 'Child' for age < 18
b. 'Adult' for age 18–60
c. 'Senior' for age > 60
d. Use: apply() or np.where() or custom function  

In [26]:
import numpy as np
data['age_group'] = np.where(data['age'] < 18, 'Child',
                             np.where(data['age'] <= 60, 'Adult', 'Senior'))
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult

9.  Display the top 5 passengers who paid the highest fare.

In [27]:
data.sort_values(by='fare', ascending=False).head(5)

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

10. Find the average fare paid, grouped by both pclass and sex.

In [28]:
data.groupby(['pclass', 'sex'])['fare'].mean()

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

11. Rename the following columns:
a. 'sex' → 'gender'
b. 'fare' → 'ticket_fare'

In [29]:
data.rename(columns={'sex': 'gender', 'fare': 'ticket_fare'}, inplace=True)
data.head()

survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  class  \
0         0       3    male  22.0      1      0       7.2500        S  Third   
1         1       1  female  38.0      1      0      71.2833        C  First   
2         1       3  female  26.0      0      0       7.9250        S  Third   
3         1       1  female  35.0      1      0      53.1000        S  First   
4         0       3    male  35.0      0      0       8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult

12. Count the number of passengers who survived and didn’t survive, grouped by class.

In [30]:
 data.groupby('pclass')['survived'].value_counts()

pclass  survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

13. Find the average age of passengers grouped by both class and gender.

In [31]:
data.groupby(['pclass', 'gender'])['age'].mean()

pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64