<a href="https://colab.research.google.com/github/ashirmuhd/DSA/blob/main/Nympy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np

a = np.arange(10,50).reshape(4,10)
a.shape
a[:,1]

array([11, 21, 31, 41])

2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [ ]:
a1 = np.full((3,3),5)
a2 = np.arange(1,10).reshape(3,3)
add = (a1+a2)
mul = (a1*a2)
trs = np.transpose(mul)
print("ADD :",add )
print("MUL :",mul )
print("TRS :",trs )



ADD : [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
MUL : [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
TRS : [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


 Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.


In [ ]:
a = np.random.randint(10,100,size=15)
c = 0
for i in range(len(a)):
  if a[i] > 50:
    a[i] = -1
    c +=1

print(c)


9


4. Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:X = x-min /max-min

In [ ]:
a = np.random.rand(5,4)
max_sum = np.argmax(np.sum(a,axis=1))
min = np.min(a)
max = np.max(a)
norm = a - min / max -min
print("Array :",a)
print("max row:",max_sum)
print("Norm",norm)


Array : [[0.44565477 0.0763855  0.20426779 0.55086545]
 [0.58430482 0.67265616 0.94869653 0.14513041]
 [0.32183833 0.18480034 0.17250436 0.72193715]
 [0.55899839 0.42963644 0.65687836 0.23331727]
 [0.04255276 0.49275887 0.25760984 0.24632478]]
max row: 1
Norm [[ 0.35824809 -0.01102117  0.11686112  0.46345877]
 [ 0.49689815  0.58524949  0.86128985  0.05772373]
 [ 0.23443165  0.09739366  0.08509768  0.63453047]
 [ 0.47159172  0.34222977  0.56947169  0.14591059]
 [-0.04485392  0.4053522   0.17020317  0.15891811]]


5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [ ]:

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]
print("Unique Elements:",unique)
print("Duplicate elements:", duplicates)



Unique Elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

In [ ]:
a = np.arange(1,37).reshape(6,6)
m = a[1:5,1:5]
e = m[m%2 ==0]
print("ARRAY:",a)
print("SUB_MATRIX:",m)
print("EVEN_NO_FROM_SUB_MATRIX:",e)

ARRAY: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
SUB_MATRIX: [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
EVEN_NO_FROM_SUB_MATRIX: [ 8 10 14 16 20 22 26 28]


7.Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [ ]:
a = np.arange(0,12).reshape(2,6)
b = a.flatten()
c = b.reshape(4,3)
print("ARRAY:",a)
print("FLATTEN_ARRAY",b)
print("CONVERTED ARRAY:",c)


ARRAY: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
FLATTEN_ARRAY [ 0  1  2  3  4  5  6  7  8  9 10 11]
CONVERTED ARRAY: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8. Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5,6])
c = np.array([ [7] , [8] , [9]])
d = np.vstack((a,b))
e = np.hstack((d,c))
print("ARRAY",a)
print("NEW ROW:",d)
print("NEW COL:",e)

ARRAY [[1 2]
 [3 4]]
NEW ROW: [[1 2]
 [3 4]
 [5 6]]
NEW COL: [[1 2 7]
 [3 4 8]
 [5 6 9]]


9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.concatenate((a,b,c))
e = d.reshape(3,3)
f = np.diag(e)
print("JOINED ARRAY :",d)
print("RESHAPED :",e)
print("DIAGONAL_ELEMENTS",f)

JOINED ARRAY : [1 2 3 4 5 6 7 8 9]
RESHAPED : [[1 2 3]
 [4 5 6]
 [7 8 9]]
DIAGONAL_ELEMENTS [1 5 9]


10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [ ]:
a = np.arange(1,21)
b = a[(a %3 == 0) |(a % 5 ==0)]
c = b.size
print("ARRAY :",a)
print("DIV:",b)
print("COUNT_DIV:",c)

ARRAY : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
DIV: [ 3  5  6  9 10 12 15 18 20]
COUNT_DIV: 9
